### PR TITLE
Frontend Enhancements

### PR DESCRIPTION
**Pull request by JefferyMeverden**
# Frontend Enhancements

#161 
#163 
#205 
#168 

# Changes

* Fixed Main Title Alignment.
* Fixed Two Typos on the Home Page.
* Fixed Loot Generator Wordage.
* Rounded Loot Hoard Value to Hundredths Place.
* Fixed Banner Horizontal Scaling.
* Suggested A Horizontal Padding Change to Make a More Responsive Navbar on Mobile.

### CODE REVIEW

**Review by johnrtabor — DISMISSED** [review]

**Comment by schiltz3** [comment]
Missing `text-align center` on `title-bar` for homepage title alignment on smaller screens/zoomed in.
I believe this is what #161 was for. I didn't add any description, so that's on me

**Review by schiltz3 — DISMISSED** [review]
see comment

**Comment by schiltz3** [comment]
I think for #163 we wanted the functionality changed from 
image

to

image
which needs `min-width: min-content` to be added to the image to keep it from shrinking, and `overflow: clip` on the `container-fluid` class to keep the image from overflowing

**Comment by schiltz3** [comment]
the #205 and #168 changes look good 🚀

**Review by schiltz3 — APPROVED** [review]

**Review by RonenLoundy — APPROVED** [review]

**Pull request merged**
